ominicontacto/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('ominicontacto_app.urls')),
    url(r'^', include('reciclado_app.urls')),
    url(r'^', include('reportes_app.urls')),
    url(r'^', include('configuracion_telefonia_app.urls')),
    url(r'^accounts/logout/$', auth_views.logout,
        {'next_page': '/accounts/login/'}, name="logout"),

]

reportes_app/urls.py
# -*- coding: utf-8 -*-
# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#

from django.conf.urls import url

from ominicontacto_app.auth.decorators import permiso_administracion_requerido

from reportes_app import views_reportes_agentes
from reportes_app.views import (ReporteLlamadasFormView, ExportarReporteLlamadasFormView,
                                ExportarZipReportesLlamadasFormView)
from reportes_app import (views_campanas_preview_reportes, views_campanas_dialer_reportes,
                          views_reportes, views_api_supervision)

urlpatterns = [
    # ==========================================================================
    # Reportes generales agentes
    # ==========================================================================
    url(r'^reportes/agentes_tiempos/$',
        permiso_administracion_requerido(
            views_reportes_agentes.ReportesTiemposAgente.as_view()),
        name='reportes_agentes_tiempos'),
    url(r'^reportes/agentes_export/(?P<tipo_reporte>[\w\-]+)/$',
        permiso_administracion_requerido(
            views_reportes_agentes.exporta_reporte_agente_llamada_view),
        name='reportes_agentes_exporta'),
    url(r'^reportes/agente_por_fecha/$',
        permiso_administracion_requerido(
            views_reportes_agentes.reporte_por_fecha_modal_agente_view),
        name='reportes_agente_por_fecha'),
    url(r'^reportes/pausa_por_fecha/$',
        permiso_administracion_requerido(
            views_reportes_agentes.reporte_por_fecha_pausa_modal_agente_view),
        name='reportes_pausa_por_fecha'),
    # ==========================================================================
    # Reportes generales llamadas
    # ==========================================================================
    url(r'^reporte/llamadas/$',
        permiso_administracion_requerido(ReporteLlamadasFormView.as_view()),
        name='reporte_llamadas',
        ),
    url(r'^reporte/llamadas/exportar/$',
        permiso_administracion_requerido(ExportarReporteLlamadasFormView.as_view()),
        name='csv_reporte_llamadas',
        ),
    url(r'^reporte/llamadas/zip/$',
        permiso_administracion_requerido(ExportarZipReportesLlamadasFormView.as_view()),
        name='zip_reportes_llamadas',
        ),
    # ==========================================================================
    # Reportes desde las campañas
    # ==========================================================================
    url(r'^campana/(?P<pk_campana>\d+)/reporte_calificacion/$',
        permiso_administracion_requerido(
            views_reportes.CampanaReporteCalificacionListView.as_view()),
        name="campana_reporte_calificacion"),
    url(r'^campana/(?P<pk_campana>\d+)/reporte_grafico/$',
        permiso_administracion_requerido(
            views_reportes.CampanaReporteGraficoView.as_view()),
        name='campana_reporte_grafico',
        ),
    url(r'^campana/(?P<pk_campana>\d+)/reporte_pdf/$',
        permiso_administracion_requerido(
            views_reportes.ExportaCampanaReportePDFView.as_view()),
        name="campana_reporte_pdf"),
    url(r'^campana/(?P<pk_campana>\d+)/reporte_grafico/(?P<pk_agente>\d+)/agente/$',
        permiso_administracion_requerido(
            views_reportes.AgenteCampanaReporteGrafico.as_view()),
        name='campana_reporte_agente',
        ),
    url(r'^campana/(?P<pk_campana>\d+)/exporta/$',
        permiso_administracion_requerido(
            views_reportes.ExportaReporteCampanaView.as_view()),
        name='exporta_campana_reporte',
        ),
    url(r'^formulario/(?P<pk_campana>\d+)/exporta/$',
        permiso_administracion_requerido(
            views_reportes.ExportaReporteFormularioVentaView.as_view()),
        name='exporta_formulario_reporte',
        ),
    url(r'^campana/(?P<pk_campana>\d+)/exporta_contactados/$',
        permiso_administracion_requerido(
            views_reportes.ExportaReporteContactadosView.as_view()),
        name='exporta_reporte_contactados',
        ),
    url(r'^campana_dialer/(?P<pk_campana>\d+)/exporta_calificados/$',
        permiso_administracion_requerido(
            views_reportes.ExportaReporteCalificadosView.as_view()),
        name='exporta_reporte_calificados',
        ),
    url(r'^campana/(?P<pk_campana>\d+)/exporta/no_atendidos/$',
        permiso_administracion_requerido(
            views_reportes.ExportaReporteNoAtendidosView.as_view()),
        name='exporta_reporte_no_atendidos',
        ),
    url(r'^campana_preview/(?P<pk>\d+)/detalle/$',
        permiso_administracion_requerido(
            views_campanas_preview_reportes.CampanaPreviewDetailView.as_view()),
        name="campana_preview_detalle"),
    url(r'^campana_preview/(?P<pk>\d+)/detalle_express/$',
        permiso_administracion_requerido(
            views_campanas_preview_reportes.CampanaPreviewExpressView.as_view()),
        name="campana_preview_detalle_express"),
    url(r'^campana_dialer/detalle_wombat/$',
        permiso_administracion_requerido(
            views_campanas_dialer_reportes.detalle_campana_dialer_view),
        name="campana_dialer_detalle_wombat"),
    url(r'^campana_dialer/(?P<pk_campana>\d+)/detalle/$',
        permiso_administracion_requerido(
            views_campanas_dialer_reportes.CampanaDialerDetailView.as_view()),
        name='campana_dialer_detalle',
        ),
    # ==========================================================================
    # Api Supervision
    # ==========================================================================
    url(r'^api_supervision/llamadas_campana/(?P<pk_campana>\d+)/$',
        views_api_supervision.LlamadasDeCampanaView.as_view(),
        name='api_supervision_llamadas_campana',
        ),
    url(r'^api_supervision/calificaciones_campana/(?P<pk_campana>\d+)/$',
        views_api_supervision.CalificacionesDeCampanaView.as_view(),
        name='api_supervision_calificaciones_campana',
        ),
]

reportes_app/forms.py
# -*- coding: utf-8 -*-
# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
from __future__ import unicode_literals

import json

from django.utils.translation import ugettext as _
from django import forms

from ominicontacto_app.utiles import convert_fecha_datetime


EMPTY_CHOICE = ('', '---------')


class ReporteAgentesForm(forms.Form):
    """
    El form para reporte con fecha
    """
    fecha = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    agente = forms.MultipleChoiceField(required=False, choices=())
    grupo_agente = forms.ChoiceField(required=False, choices=(), widget=forms.Select(
        attrs={'class': 'form-control'}))
    todos_agentes = forms.BooleanField(required=False)

    def __init__(self, agentes_asociados, grupos_asociados, *args, **kwargs):
        super(ReporteAgentesForm, self).__init__(*args, **kwargs)

        agente_choice = [(agente.pk, agente.user.get_full_name())
                         for agente in agentes_asociados]
        self.fields['agente'].choices = agente_choice
        grupo_choice = [(grupo.id, grupo.nombre)
                        for grupo in grupos_asociados]
        grupo_choice.insert(0, EMPTY_CHOICE)
        self.fields['grupo_agente'].choices = grupo_choice


class ReporteLlamadasForm(forms.Form):
    """
    El form para reporte de llamadas
    """
    fecha = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    finalizadas = forms.BooleanField(required=False, label=_(u'Incluir campañas finalizadas'))

    def clean_fecha(self):
        fecha = self.cleaned_data.get('fecha')
        try:
            fecha_desde, fecha_hasta = fecha.split('-')
            fecha_desde = convert_fecha_datetime(fecha_desde)
            fecha_hasta = convert_fecha_datetime(fecha_hasta, final_dia=True)
        except ValueError:
            raise forms.ValidationError(_('Formato inválido'))
        self.desde = fecha_desde
        self.hasta = fecha_hasta
        return fecha


class EstadisticasJSONForm(forms.Form):
    estadisticas = forms.CharField()

    def clean_estadisticas(self):
        estadisticas = self.cleaned_data.get('estadisticas')
        try:
            json_data = json.loads(estadisticas)
        except ValueError:
            raise forms.ValidationError(_(u'Formato JSON invalido'))
        return json_data


TIPO_REPORTE_CHOICES = (
    ('llamadas_por_tipo', ''),
    ('llamadas_por_campana', ''),
    ('tipos_de_llamada_manual', ''),
    ('tipos_de_llamada_dialer', ''),
    ('tipos_de_llamada_entrante', ''),
    ('tipos_de_llamada_preview', ''),
)


class ExportarReporteLlamadasForm(EstadisticasJSONForm):
    tipo_reporte = forms.ChoiceField(choices=TIPO_REPORTE_CHOICES, required=True)

reportes_app/views.py
# -*- coding: utf-8 -*-
# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#

from __future__ import unicode_literals

import json
from StringIO import StringIO
from zipfile import ZipFile

from django.utils.timezone import now
from django.views.generic import FormView
from django.http import HttpResponse

from ominicontacto_app.utiles import datetime_hora_minima_dia, UnicodeWriter
from ominicontacto_app.views_utils import handler400

from reportes_app.forms import (ReporteLlamadasForm, ExportarReporteLlamadasForm,
                                EstadisticasJSONForm)
from reportes_app.reporte_llamadas import ReporteDeLlamadas, GeneradorReportesLlamadasCSV


class ReporteLlamadasFormView(FormView):
    """Vista que despliega reporte de las grabaciones de las llamadas"""
    template_name = 'reporte_llamadas.html'
    form_class = ReporteLlamadasForm

    def get_initial(self):
        initial = super(ReporteLlamadasFormView, self).get_initial()
        hoy = now().date().strftime('%d/%m/%Y')
        initial['fecha'] = ' - '.join([hoy] * 2)
        return initial

    def get(self, request, *args, **kwargs):
        hoy_ahora = now()
        hoy_inicio = datetime_hora_minima_dia(hoy_ahora)
        reporte = ReporteDeLlamadas(hoy_inicio, hoy_ahora, False, request.user)
        return self.render_to_response(self.get_context_data(
            desde=hoy_inicio,
            hasta=hoy_ahora,
            estadisticas=reporte.estadisticas,
            graficos=reporte.graficos,
            estadisticas_por_fecha=reporte.estadisticas_por_fecha,
            estadisticas_json=json.dumps(reporte.estadisticas)))

    def form_valid(self, form):
        desde = form.desde
        hasta = form.hasta
        finalizadas = form.cleaned_data['finalizadas']
        reporte = ReporteDeLlamadas(desde, hasta, finalizadas, self.request.user)
        return self.render_to_response(self.get_context_data(
            desde=desde,
            hasta=hasta,
            estadisticas=reporte.estadisticas,
            graficos=reporte.graficos,
            estadisticas_por_fecha=reporte.estadisticas_por_fecha,
            estadisticas_json=json.dumps(reporte.estadisticas)))


class ExportarReporteLlamadasFormView(FormView):
    form_class = ExportarReporteLlamadasForm

    def form_valid(self, form):
        response = HttpResponse(content_type='text/csv')
        estadisticas = form.cleaned_data.get('estadisticas')
        tipo_reporte = form.cleaned_data.get('tipo_reporte')

        response['Content-Disposition'] = 'attachment; filename="{0}.csv"'.format(tipo_reporte)
        writer = UnicodeWriter(response)

        generador = GeneradorReportesLlamadasCSV()
        filas_csv = generador.obtener_filas_reporte(estadisticas, tipo_reporte)
        writer.writerows(filas_csv)
        # writer.writerow(REPORTE_SIN_DATOS)

        return response

    def form_invalid(self, form):
        return handler400(self.request)


class ExportarZipReportesLlamadasFormView(FormView):
    form_class = EstadisticasJSONForm

    def form_valid(self, form):
        """
        Realiza la exportación de todos los reportes de llamadas a .csv y los devuelve
        comprimidos dentro de un zip
        """
        estadisticas = form.cleaned_data.get('estadisticas')

        buffer = self._generar_buffer_archivo_zip(estadisticas)

        response = HttpResponse(content_type="application/zip")
        response["Content-Disposition"] = "attachment; filename=reporte-general.zip"

        buffer.seek(0)
        response.write(buffer.read())

        return response

    def form_invalid(self, form):
        return handler400(self.request)

    def _generar_buffer_archivo_zip(self, estadisticas):

        generador = GeneradorReportesLlamadasCSV()
        (llamadas_por_tipo, llamadas_por_campana, tipos_de_llamada_manual,
         tipos_de_llamada_dialer, tipos_de_llamada_entrante,
         tipos_de_llamada_preview) = generador.obtener_filas_de_todos_los_reportes(estadisticas)

        in_memory = StringIO()
        zip = ZipFile(in_memory, "a")

        llamadas_por_tipo_file = StringIO()
        llamadas_por_tipo_writer = UnicodeWriter(llamadas_por_tipo_file)
        llamadas_por_tipo_writer.writerows(llamadas_por_tipo)

        llamadas_por_campana_file = StringIO()
        llamadas_por_campana_writer = UnicodeWriter(llamadas_por_campana_file)
        llamadas_por_campana_writer.writerows(llamadas_por_campana)

        tipos_de_llamada_manual_file = StringIO()
        tipos_de_llamada_manual_writer = UnicodeWriter(tipos_de_llamada_manual_file)
        tipos_de_llamada_manual_writer.writerows(tipos_de_llamada_manual)

        tipos_de_llamada_dialer_file = StringIO()
        tipos_de_llamada_dialer_writer = UnicodeWriter(tipos_de_llamada_dialer_file)
        tipos_de_llamada_dialer_writer.writerows(tipos_de_llamada_dialer)

        tipos_de_llamada_entrante_file = StringIO()
        tipos_de_llamada_entrante_writer = UnicodeWriter(tipos_de_llamada_entrante_file)
        tipos_de_llamada_entrante_writer.writerows(tipos_de_llamada_entrante)

        tipos_de_llamada_preview_file = StringIO()
        tipos_de_llamada_preview_writer = UnicodeWriter(tipos_de_llamada_preview_file)
        tipos_de_llamada_preview_writer.writerows(tipos_de_llamada_preview)

        zip.writestr("llamadas_por_tipo.csv", llamadas_por_tipo_file.getvalue())
        zip.writestr("llamadas_por_campana.csv", llamadas_por_campana_file.getvalue())
        zip.writestr("tipos_de_llamada_manual.csv", tipos_de_llamada_manual_file.getvalue())
        zip.writestr("tipos_de_llamada_dialer.csv", tipos_de_llamada_dialer_file.getvalue())
        zip.writestr("tipos_de_llamada_entrante.csv", tipos_de_llamada_entrante_file.getvalue())
        zip.writestr("tipos_de_llamada_preview.csv", tipos_de_llamada_preview_file.getvalue())

        # fix for Linux zip files read in Windows
        for file in zip.filelist:
            file.create_system = 0
        zip.close()

        return in_memory

reportes_app/templates/calificaciones_campana.html
<!--
Copyright (C) 2018 Freetech Solutions

This file is part of OMniLeads

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see http://www.gnu.org/licenses/.

-->
{% extends "base.html" %}
{% load static %}

{% block content %}

                <h1>Campaña {{ campana.nombre }}</h1>

                {% if campana.fecha_inicio %}
                    <h3>Desde: {{ campana.fecha_inicio|date:"d/m/Y" }}</h3>
                    <h3>Hasta: {{ campana.fecha_fin|date:"d/m/Y" }}</h3>
                {% endif %}
                <h3>Base Datos: {{ campana.bd_contacto }}</h3>
                <br>
                <a class="btn btn-outline-primary" href="{% url 'exporta_campana_reporte' campana.pk %}">Exportar Calificacion(CSV)</a>
                <a class="btn btn-outline-primary" href="{% url 'exporta_formulario_reporte' campana.pk %}">Exportar Gestion: {{campana.gestion}}(CSV)</a>
                <table class="table">
                    <thead>
                      <tr class="fts-table-bg">
                        <th>Teléfono</th>
                        <th>Datos</th>
                        <th>Calificación</th>
                        <th>Observaciones</th>
                        <th>Base de datos</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for calificacion in campana.obtener_calificaciones %}
                            <tr>
                                <td>
                                    {{ calificacion.contacto.telefono }}
                                </td>
                                <td>
                                    {{ calificacion.contacto.datos}}
                                </td>
                                 <td>
                                    {{ calificacion.opcion_calificacion.nombre }}
                                </td>
                                <td>
                                    {% if calificacion.observaciones %}
                                        {{calificacion.observaciones}}
                                    {% endif %}
                                </td>
                                <td>{{calificacion.contacto.bd_contacto}}</td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="16">
                                    <p>No se encontraron Calificaciones para esta campaña.</p>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
{% endblock %}

reportes_app/templates/reporte_agente.html
<!--
Copyright (C) 2018 Freetech Solutions

This file is part of OMniLeads

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see http://www.gnu.org/licenses/.

-->
{% extends "base.html" %}
{% load static %}
{% block head_js %}
<script type="text/javascript">
   $(function() {
                var start = moment();
                var end = moment();
                function cb(start, end) {
                    $('#id_fecha').html(start.format('DD/MM/YYYY') + ' - ' + end.format('DD/MM/YYYY'));
                }

 $('#id_fecha').on('apply.daterangepicker', function(ev, picker) {
      $(this).val(picker.startDate.format('DD/MM/YYYY') + ' - ' + picker.endDate.format('DD/MM/YYYY'));
  });

  $('#id_fecha').on('cancel.daterangepicker', function(ev, picker) {
      $(this).val('');
});

            // Init daterange plugin
            $('#id_fecha').daterangepicker(
                {
                locale: {
                    format: 'DD/MM/YYYY'
                 },

                startDate: start,
                endDate: end,
                ranges: {
                    'Hoy': [moment(), moment()],
                    'Ayer': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                    'Ultimos 7 Días': [moment().subtract(6, 'days'), moment()],
                    'Ultimos 30 Días': [moment().subtract(29, 'days'), moment()],
                    'Este Mes': [moment().startOf('month'), moment().endOf('month')],
                    'Ultimo Mes': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
                },

        }, cb);

        cb(start, end);

});
    </script>
{% endblock %}
{% block content %}
 <script type="text/javascript" src="{% static 'ominicontacto/JS/pygal-tooltips.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'ominicontacto/JS/pygal-tooltips.js' %}"></script>



{% with graficos_estadisticas=graficos_estadisticas %}
<div class="col-md-12">
    <h4>Agente {{agente.user.get_full_name}}</h4>
</div>
<div class="col-md-6">

    <form role="form" method="post" enctype="multipart/form-data" >
        {% csrf_token %}
        <table class="table">
           <tr>
               <td>
                   <div class="input-group date pull-right active" id="">
                       {{form.fecha}}
                        <span class="input-group-addon cursor"><i class="fa fa-calendar"></i>
                        </span>
                    </div>
               </td>
               <td>
                   <button type="submit" id="id_buscar_btn" class="btn btn-primary">
                        Filtrar por esa fecha
                </button>
               </td>
           </tr>
        </table>

    </form>
</div>




                <table class="table table-bordered">
                        <thead>
                            <tr class="fts-table-bg">
                                <td colspan="2">
                                    <h4>Cantidad de calificacion por el agente</h4>
                                </td>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td width="50%">
                                    <table class="table table-bordered">
                                        <thead>
                                        <tr>
                                            <th>Calificacion</th>
                                            <th>cantidad </th>


                                        </tr>
                                        </thead>
                                        <tbody>
                                            {% for calificaciones_nombre, calificaciones_cantidad in graficos_estadisticas.dict_campana_counter %}
                                                <tr>
                                                    <td><h5>{{ calificaciones_nombre }} </h5></td>
                                                    <td><h5>{{ calificaciones_cantidad }} </h5></td>
                                                </tr>
                                            {% endfor %}
                                                <tr>
                                                    <td><strong>Total asignados</strong></td>
                                                    <td><strong>{{graficos_estadisticas.total_asignados}}</strong></td>
                                                </tr>
                                        </tbody>
                                    </table>
                                </td>
                                <td width="50%" align="center">
                                    <div class="graficos-avances">
                                        <figure>
                                            {{ graficos_estadisticas.barra_campana_calificacion.render|safe }}
                                        </figure>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Tiempo en sesión</th>
            <th>Tiempo en pausa</th>
            <th>Tiempo en llamada</th>
            <th>Porcentaje en llamada</th>
            <th>Porcentaje en pausa</th>
            <th>Porcentaje en espera</th>
            <th>Cantidad de llamadas procesadas</th>
            <th>Tiempo promedio de llamadas</th>
            <th>Cantidad de intentos fallidos</th>
        </tr>
    </thead>

        <tr>
            <td>{{graficos_estadisticas.estadisticas.agente_tiempo.get_string_tiempo_sesion|default_if_none:0}}hs</td>
            <td>{{graficos_estadisticas.estadisticas.agente_tiempo.get_string_tiempo_pausa|default_if_none:0}}hs</td>
            <td>{{graficos_estadisticas.estadisticas.agente_tiempo.get_string_tiempo_llamada|default_if_none:0}}hs</td>
            <td>{{graficos_estadisticas.estadisticas.agente_tiempo.tiempo_porcentaje_llamada|default_if_none:0}}</td>
            <td>{{graficos_estadisticas.estadisticas.agente_tiempo.tiempo_porcentaje_pausa|default_if_none:0}}</td>
            <td>{{graficos_estadisticas.estadisticas.agente_tiempo.tiempo_porcentaje_wait|default_if_none:0}}</td>
            <td>{{graficos_estadisticas.estadisticas.agente_tiempo.cantidad_llamadas_procesadas}}</td>
            <td>{{graficos_estadisticas.estadisticas.agente_tiempo.tiempo_promedio_llamadas|default_if_none:0}}s</td>
            <td>{{graficos_estadisticas.estadisticas.agente_tiempo.cantidad_llamadas_perdidas}}</td>
        </tr>

    <tbody>

    </tbody>
</table>



<div class="col-md-12">
    <a class="btn btn-default"  href="{% url 'campana_reporte_grafico' pk_campana %}">Volver a reporte campana</a>

</div>

{% endwith %}
{% endblock %}

reportes_app/templates/tbody_fechas_agentes.html
<!--
Copyright (C) 2018 Freetech Solutions

This file is part of OMniLeads

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see http://www.gnu.org/licenses/.

-->
{% for agente in agentes %}
        <tr>
            <td>
                 {{agente.agente}}
            </td>
            <td>
                {% if agente.get_string_tiempo_sesion %}
                    {{agente.get_string_tiempo_sesion}}hs
                {% else %}
                    0hs
                {% endif %}
            </td>
            <td>
                {% if agente.get_string_tiempo_pausa %}
                    {{agente.get_string_tiempo_pausa}}hs
                {% else %}
                    0hs
                {% endif %}
            </td>
            <td>{{agente.get_string_tiempo_llamada}}hs</td>
            <td>
                {% if agente.tiempo_porcentaje_llamada %}
                    {{agente.tiempo_porcentaje_llamada|floatformat:4}}%
                {% else %}
                    0%
                {% endif %}
            </td>
            <td>
                {% if agente.tiempo_porcentaje_pausa %}
                    {{agente.tiempo_porcentaje_pausa|floatformat:4}}%
                {% else %}
                    0%
                {% endif %}
            </td>
            <td>
                {% if agente.tiempo_porcentaje_wait %}
                    {{agente.tiempo_porcentaje_wait|floatformat:4}}%
                {% else %}
                    0%
                {% endif %}
            </td>
            <td>{{agente.cantidad_llamadas_procesadas}}</td>
            <td>{{agente.get_promedio_llamadas}}s</td>
            <td>{{agente.cantidad_intentos_fallidos}}</td>
        </tr>
{% endfor %}

reportes_app/templates/tbody_pausa_fechas_agentes.html
<!--
Copyright (C) 2018 Freetech Solutions

This file is part of OMniLeads

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see http://www.gnu.org/licenses/.

-->
    {% for agente in agentes %}
        <tr>
            <td>{{agente.fecha}}</td>
            <td>{{agente.tiempo}}hs</td>
        </tr>
    {% endfor %}